### ISSUE TITLE
TypeError: Converting py args to operator properties:  EXPORT_SCENE_OT_gltf.export_materials expected True/False or 0/1, not str

### ISSUE THREAD

**Issue by AgentSmith0** [Takanu/GEX#29]
When clicking on 'Export All', I get the following error message:
```
Traceback (most recent call last):
  File "/home/me/.config/blender/2.83/scripts/addons/Capsule/export_operators.py", line 95, in execute
    object_export_result = ExportObjectList(context, exp, export_objects, global_record)
  File "/home/me/.config/blender/2.83/scripts/addons/Capsule/export_operators.py", line 315, in ExportObjectList
    export_result = ExportTarget(context, [item], item.name, export_preset, location_preset, origin_point, item, meta)
  File "/home/me/.config/blender/2.83/scripts/addons/Capsule/export_operators.py", line 487, in ExportTarget
    PrepareExportCombined(context, targets, path, export_preset, export_name)
  File "/home/me/.config/blender/2.83/scripts/addons/Capsule/export_operators.py", line 544, in PrepareExportCombined
    export_preset.data_gltf.export(context, export_preset, path, export_name)
  File "/home/me/.config/blender/2.83/scripts/addons/Capsule/export_formats/export_format_gltf.py", line 274, in export
    bpy.ops.export_scene.gltf(
  File "/usr/share/blender/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  EXPORT_SCENE_OT_gltf.export_materials expected True/False or 0/1, not str

location: <unknown location>:-1
```
I have set all options, including File Location and Export Preset. I also checked 'Enable Export'. I also watched this video: https://www.youtube.com/watch?v=P20m2JBgNnA

**Comment by AgentSmith0** [comment]
It looks like I was just using a too old Blender version. With Blender 2.93.2 (latest) it works well, but when I first click the export button it gives me still an error (like in the video). At the second try after clicking again on Origin Export -> Object, I was able to export. Anyway, thank you very much!
